### ISSUE TITLE
Raw metric is pretty unusable

### ISSUE THREAD

**Issue by fizyk** [WoLpH/python-statsd#35]
We've just started using Raw metrics, but it seems it's pretty unusable. 

I've made an issue report against statsd: https://github.com/etsy/statsd/issues/467

But so far it seems like tha statsd accepts only rate as the third element, not timestamp of any kind.

I even had a problem finding the Raw issue mentioned anywhere outside of python-statsd or statsd itself

**Comment by WoLpH** [comment]
Since the upstream issue has been closed, very little I can do here
