### ISSUE TITLE
not compatible with latest python-statsd

### ISSUE THREAD

**Issue by cblomart** [WoLpH/python-statsd#43]
connection defined via python-statsd Connection object.

Excrept of the error:
  File "/usr/lib/python2.7/site-packages/wsgi_statsd/__init__.py", line 101, in send_stats
    timer = self.statsd_client.timer(key_name)
AttributeError: 'Client' object has no attribute 'timer'

**Comment by WoLpH** [comment]
For future reference. You can fetch a timer using `get_timer()`: http://python-statsd.readthedocs.io/en/latest/statsd.client.html#statsd.client.Client.get_timer
