### ISSUE TITLE
comparison to pystatsd

### ISSUE THREAD

**Issue by wbolster** [WoLpH/python-statsd#44]
this project seems more active than pystatsd (https://github.com/jsocol/pystatsd), though both have very similar feature sets.

can you explain why one would choose one over the other? thanks! :)

**Comment by WoLpH** [comment]
The projects are actually quite similar in features and possibilities so it's mostly a matter of taste :)

Personally I think this project uses a more Pythonic API which makes usage easier and clearer. To illustrate:

This project (as taken from the docs):
```
import statsd
counter = statsd.Counter('MyApplication')
# The actual increment
counter += 1
```
The other project (as taken from the docs):
```
from statsd import StatsClient
statsd = StatsClient()
statsd.incr('MyApplication')
```

I would argue that being able to increase/decrease by using `+=` and `-=` is more obvious but you have the choice available. If you wish, `counter.increment()` is also available.

In the end it mostly comes down to preference :)
If you are using Django you can also take a look at another project of mine which uses this one internally: https://github.com/WoLpH/django-statsd

**Comment by wbolster** [comment]
thanks for your answer btw!
